sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    class:
        user: App\Entity\User
        group: App\Entity\Group

# sonata_user:
#     security_acl: true
#     manager_type: orm # can be orm or
#     class:
#         user: Application\Sonata\UserBundle\Entity\User
#         group: Application\Sonata\UserBundle\Entity\Group
#     admin:                  # Admin Classes
#         user:
#             class:          Application\Sonata\UserBundle\Admin\UserAdmin # there define your extended admin class
#             controller:     SonataUserBundle:UserCURD
#             translation:    SonataUserBundle