twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: 
        - 'bootstrap_4_layout.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - '@SonataCore/Form/color.html.twig'
    paths:
        '%kernel.project_dir%/src/BlockManager/templates': BlockManagerTemplates
    globals:
        config: "@app.config"