admin_area:
    host: "admin.{domain}"
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    defaults:
        domain: '%base_host%'
    requirements:
        domain: '%base_host%'

_sonata_admin:
    host: "admin.{domain}"
    resource: .
    type: sonata_admin
    prefix: /admin
    defaults:
        domain: '%base_host%'
    requirements:
        domain: '%base_host%'
