<?php

namespace App\Model;

use Symfony\Component\HttpFoundation\File\UploadedFile;

class ImportFile {

    /**
    * Unmapped property to handle file uploads
    */
    private $file;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid()).'.'.$this->getFile()->guessExtension();
    }
}