config:
    vars:
        event_date:
            type: DateTime
            form_type: Sonata\CoreBundle\Form\Type\DateTimePickerType
            group: config.wedding.group
            label: config.wedding.date
            show: true
        page_title:
            type: string
            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
            form_options:
                required: false
            group: config.general.group
            label: config.general.title
            show: true
        panel_text_1:
            type: string
            form_type: FOS\CKEditorBundle\Form\Type\CKEditorType
            form_options:
                required: false
            group: config.general.group
            label: config.general.text1
            show: true
        panel_text_2:
            type: string
            form_type: FOS\CKEditorBundle\Form\Type\CKEditorType
            form_options:
                required: false
            group: config.general.group
            label: config.general.text2
            show: true
        navbar_show_login:
            type: boolean
            form_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            form_options:
                required: false
            group: config.general.group
            label: config.general.navbar_show_login
            default: true
            show: true
        newlyweds:
            type: string
            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
            form_options:
                required: false
            group: config.wedding.group
            label: config.wedding.name
            show: true
        navbar_title:
            type: string
            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
            group: config.general.group
            label: config.general.navbar_title
            show: true
        gift_enabled:
            type: boolean
            form_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            form_options:
                required: false
            group: config.gift.group
            label: config.gift.enabled
            show: true
        gift_show_chosen:
            type: boolean
            form_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            form_options:
                required: false
            group: config.gift.group
            label: config.gift.show_chosen
            show: true
        gift_multiple_choice:
            type: boolean
            form_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            form_options:
                required: false
            group: config.gift.group
            label: config.gift.multiple
            show: true