block_manager:
    blocks:
        text:
            tag: block.text
            name: Text block
            manager: App\BlockManager\Blocks\TextBlock\TextBlockManager
            model: App\BlockManager\Blocks\TextBlock\TextBlock
            form: App\BlockManager\Blocks\TextBlock\TextBlockForm