block_manager:
    blocks:
        text:
            tag: block.text
            name: Text block
            manager: App\BlockManager\Blocks\TextBlock\TextBlockManager
            model: App\BlockManager\Blocks\TextBlock\TextBlock
            form: App\BlockManager\Blocks\TextBlock\TextBlockForm
        counter_header:
            tag: block.counter_header
            name: Counter header
            manager: App\BlockManager\Blocks\CounterHeader\CounterHeaderManager
            model: App\BlockManager\Blocks\CounterHeader\CounterHeader
            form: App\BlockManager\Blocks\CounterHeader\CounterHeaderForm
        google_maps:
            tag: block.google_maps
            name: Maps Google
            manager: App\BlockManager\Blocks\GoogleMaps\GoogleMapsManager
            model: App\BlockManager\Blocks\GoogleMaps\GoogleMaps
            form: App\BlockManager\Blocks\GoogleMaps\GoogleMapsForm